CREATE TABLE IF NOT EXISTS BOOK (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    PUBLISHING_YEAR INTEGER,
    AUTHOR VARCHAR(255) NOT NULL,
    ISBN VARCHAR(255),
    TITLE VARCHAR(255) NOT NULL
);